name: Validate
on:
  pull_request: {}
  workflow_call: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Generate prisma client
        run: npx prisma generate

      - name: Restore node_modules
        id: cache-modules
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            node_modules/.prisma
          # Include prisma schema in hash to invalidate cache when schema changes
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

      - name: Install deps
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci && npx prisma generate

      - name: Cache node_modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            node_modules/.prisma
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

  lint:
    needs: setup
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            node_modules/.prisma
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

      - name: ğŸ–¼ Build icons
        run: npm run build:icons

      - name: ğŸ”¬ Lint
        run: npm run lint

  build:
    needs: setup
    name: ğŸ”¨ Build
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            node_modules/.prisma
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

      - name: Build
        run: npm run build

  typecheck:
    needs: setup
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            node_modules/.prisma
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

      - name: ğŸ–¼ Build icons
        run: npm run build:icons

      - name: Show TypeScript version
        run: npx tsc --version

      - name: ğŸ” Type check
        run: npm run typecheck -- --pretty

  vitest:
    needs: setup
    name: âš¡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¥ Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            node_modules/.prisma
          key:
            node-modules-${{ hashFiles('package-lock.json',
            'prisma/schema.prisma') }}

      - name: ğŸ„ Copy test env vars
        run: cp .env.example .env

      - name: ğŸ–¼ Build icons
        run: npm run build:icons

      - name: âš¡ Run vitest
        run: npm run test -- --coverage

  # Having trouble with playwright job, commenting it out for now as we're not doing much e2e testing atm
  # playwright:
  #   needs: setup
  #   name: ğŸ­ Playwright
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v4

  #     - name: ğŸ„ Copy test env vars
  #       run: cp .env.example .env

  #     - name: â” Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22

  #     - name: ğŸ“¥ Restore cache
  #       uses: actions/cache/restore@v4
  #       with:
  #         path: |
  #           node_modules
  #           node_modules/.prisma
  #         key:
  #           node-modules-${{ hashFiles('package-lock.json',
  #           'prisma/schema.prisma') }}

  #     - name: ğŸ“¥ Install Playwright Browsers
  #       run: npm run test:e2e:install

  #     - name: ğŸ›  Setup Database
  #       run: npx prisma migrate deploy

  #     - name: ğŸ¦ Cache Database
  #       id: db-cache
  #       uses: actions/cache@v4
  #       with:
  #         path: prisma/data.db
  #         key:
  #           db-cache-schema_${{
  #           hashFiles('./prisma/schema.prisma')}}-migrations_${{
  #           hashFiles('./prisma/migrations/*/migration.sql')}}

  #     - name: ğŸŒ± Seed Database
  #       if: steps.db-cache.outputs.cache-hit != 'true'
  #       run: npx prisma migrate reset --force

  #     - name: ğŸ— Build
  #       run: npm run build

  #     - name: ğŸ­ Playwright tests
  #       run: npx playwright test

  #     - name: ğŸ“Š Upload report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
